create table person(
  id int primary key generated by default as identity ,
  username varchar(100) not null,
  year_of_birth int not null ,
  password varchar not null,
  role varchar(100) not null
);

insert into person (username, year_of_birth, password) VALUES ('test_user1',1960,'test_password');
insert into person (username, year_of_birth, password) VALUES ('test_user2',1960,'test_password');